### PR TITLE
Use SSH Credentials

### PR DESCRIPTION
**Pull request by afbjorklund**
Use ssh credentials for storing ssh username and password,
instead of storing them in cleartext in the configuration.

### CODE REVIEW

**Comment by jmcgeheeiv** [comment]
Nice functionality.  It would be very nice if you could also update the README documentation.

**Comment by afbjorklund** [comment]
Actually I don't think there's anything "wrong" in the documentation, it is all in the html help ?
(basically ssh-credentials-plugin handles all the user interface, and the popup is very similar)

> Go to "Manage Jenkins"->"Configure System" and add a new cloud "LSF Cloud".
> 
> Fill in the required information to the created cloud configuration.
> Make sure that the host to which the cloud will connect has access to LSF.

**Comment by afbjorklund** [comment]
Also, there seems to be something wrong in the upgrade functionality :-(
It creates multiple entries with the username, need to look into that...

**Comment by krlmlr** [comment]
We're looking for this functionality, any chance to have it included soon-ish? Thanks!

**Comment by jmcgeheeiv** [comment]
I have not seen a lot of activity on this project since I forked it to make sge-cloud-plugin.  I do not have LSF--without the ability to test I am unqualified to merge.  @afbjorklund, perhaps you could become maintainer?

**Comment by afbjorklund** [comment]
I used [OpenLava](http://www.openlava.org/) for my testing, but it seems that IBM has now taken it down with DMCA ?

https://github.com/openlava/openlava

Which seems weird, since it was [Platform](https://en.wikipedia.org/wiki/Platform_Computing) that released Lava 1.0 (as GPLv2) themselves...

Not using LSF anymore myself, either.

**Pull request closed without merging**
